### ISSUE TITLE
--api ieee -x the warning shows, but not a graceful exit

### ISSUE THREAD

**Issue by rossmounce** [ContentMine/getpapers#36] opened 2015-06-29 16:55 UTC
When I saw the graceful exit displayed by --api arxiv -x:

```
$ getpapers -q 'Gasteria' --api arxiv -x  --outdir ./car
info: Searching using arxiv API
warn: The ArXiv API does not provide fulltext XML, so the --xml flag will be ignored
info: Found 0 results
```

I realised that even though the warning is clearly displayed, this should still be flagged as a bug because of the non-graceful exit:

```
$ getpapers -q 'Gasteria' --api ieee -x  --outdir ./car
info: Searching using ieee API
warn: The IEEE API does not provide fulltext XML, so the --xml flag will be ignored

TypeError: Cannot read property 'totalfound' of undefined
    at IEEE.completeCallback (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/lib/ieee.js:72:38)
    at Request.emit (events.js:98:17)
    at Request.mixin._fireSuccess (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/lib/restler.js:226:10)
    at /home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/lib/restler.js:158:20
    at /home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/lib/restler.js:448:9
    at Parser.<anonymous> (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/node_modules/xml2js/lib/xml2js.js:344:20)
    at Parser.emit (events.js:95:17)
    at Object.saxParser.onclosetag (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/node_modules/xml2js/lib/xml2js.js:314:24)
    at emit (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
```

**Comment by Blahah** [comment] 2015-08-01 21:08
This is unrelated to the `-x` flag. The problem is that there are 0 results from ieee, and that situation is not handled properly.

**Comment by Blahah** [comment] 2015-08-01 21:08
(dupe of #34)

**Closed by Blahah** 2015-08-01 21:08 UTC
