### ISSUE TITLE
No Output

### ISSUE THREAD

**Issue by daMogli** [ContentMine/getpapers#60] opened 2015-11-02 16:21 UTC
Is there any place I can see an error log? I issue this command:

`getpapers --query 'PMCID: PMC2732911' --all --outdir ~/test`

and nothing happens. I don't get an error or any sort of message. It works on my Mac but not my Amazon Linux machine.

**Comment by Blahah** [comment] 2015-11-02 17:47
It should output to stdout/stderr. Is there anything special about the Amazon setup?

**Comment by daMogli** [comment] 2015-11-02 18:20
It's a Unix box behind a nat with a public ip

**Comment by tarrow** [comment] 2016-02-17 14:24
I managed to replicate this bug. Turns out it is an operating system issue with ubuntu. See: http://askubuntu.com/questions/375720/node-executables-not-doing-anything

Basically there is also a package called node that is nothing to do with nodejs. I also installed it by mistake but it takes over the 'node' alias. You then need to apt-get remove --purge node and re-install nodejs.

You can verify the problem is the same if you run node --version and you still get no response

**Comment by Blahah** [comment] 2016-03-05 11:05
Closing this as @tarrow has identified a fix.

**Closed by Blahah** 2016-03-05 11:05 UTC
