### ISSUE TITLE
Potentially unhandled rejection - Error: socket hang up

### ISSUE THREAD

**Issue by lsm35** [ContentMine/getpapers#170] opened 2018-03-03 19:18 UTC
Hello, 

I run into an error if I try to download xml files using the getpapers command as below with the default eupmc api. Downloading pdfs works fine.

`getpapers -q FliK -o FliK -x -k 100`

The error happens after the metadata has been collected and new directories for each of the papers have been made. The message repeats 10 times [2],[4] etc. up to [20]. I was previously using getpapers without any problems for another project in September - so tried reinstalling it but still unfortunately get the error.

```
nanobody:ContentMine lsm35$ getpapers -q FliK -o FliK -x -k 100
info: Searching using eupmc API
info: Found 222 open access results
info: Limiting to 100 hits
Retrieving results [==============================] 100% (eta 0.0s)
info: Done collecting results
info: limiting hits
info: Saving result metadata
info: Full EUPMC result metadata written to eupmc_results.json
info: Individual EUPMC result metadata records written
info: Extracting fulltext HTML URL list (may not be available for all articles)
info: Fulltext HTML URL list written to eupmc_fulltext_html_urls.txt
warn: Article with pmcid "PMC5816901" was not Open Access (therefore no XML)
warn: Article with pmcid "PMC4713962" was not Open Access (therefore no XML)
warn: Article with pmcid "PMC5816908" was not Open Access (therefore no XML)
info: Got XML URLs for 97 out of 100 results
info: Downloading fulltext XML files
Downloading files [===---------------------------] 10% (10/97) [0.0s elapsed, eta 0.0]Potentially unhandled rejection [2] Error: socket hang up
    at createHangUpError (_http_client.js:345:15)
    at Socket.socketOnEnd (_http_client.js:437:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Potentially unhandled rejection [4] Error: socket hang up
    at createHangUpError (_http_client.js:345:15)
    at Socket.socketOnEnd (_http_client.js:437:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

In case this is useful:

```
nanobody:ContentMine lsm35$ node --version
v8.2.1
nanobody:ContentMine lsm35$ getpapers --version
0.4.16

```

I'd be very grateful if someone can help me get the xml download working! 
Thanks, Laura.

**Comment by jkbcm** [comment] 2018-03-05 17:32
Hello Laura,

Thanks for the detailed report.

This is caused by EUPMC updating their interface.  We now have a fix for this and aim to release an update soon.

**Closed** 2018-03-06 10:34 UTC
