### ISSUE TITLE
Installing getpapers on Ubuntu distros

### ISSUE THREAD

**Issue by alexmaina** [ContentMine/getpapers#101] opened 2016-05-05 15:41 UTC
I am trying to install getpapers on my ubuntu 14.04 box. However, when i run npm install --global getpapers i get the following errors

`alex@alex-Studio-1555:~$ npm install --global getpapers
npm http GET https://registry.npmjs.org/getpapers
npm http 304 https://registry.npmjs.org/getpapers
npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/getpapers',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/lib/nodejs/fstream/lib/writer.js:171:23',
npm ERR!      '/usr/lib/nodejs/mkdirp/index.js:37:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.13.0-85-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--global" "getpapers"
npm ERR! cwd /home/alex
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules
npm ERR! fstream_path /usr/local/lib/node_modules/getpapers
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/usr/local/lib/node_modules'
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/nodejs/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/alex/npm-debug.log
npm ERR! not ok code 0
`

How do i get round the problem?

I also attach the log(see below)

[npm-debug.txt](https://github.com/ContentMine/getpapers/files/250661/npm-debug.txt)

**Comment by blahah** [comment] 2016-05-05 21:34
unfortunately node setup using apt-get requires you to use sudo to install new node packages. So this should work:

```
sudo npm install --global getpapers
```

**Comment by alexmaina** [comment] 2016-05-07 09:29
Thanks....

**Comment by psychemedia** [comment] 2016-05-07 10:57
I have a Dockerfile for building contentmine tools here:  https://gist.github.com/psychemedia/fff4605eb04b40de7f1ea5d975e74873

**Comment by psychemedia** [comment] 2016-05-11 22:39
I've started sketching some magics that make it easier to call the functions contained within the `psychemedia/contentmine` container from a code cell in a Jupyter/IPython notebook: [Steps Towards Some Docker IPython Magic – Draft Magic to Call a Contentmine Container from a Jupyter Notebook Container](https://blog.ouseful.info/2016/05/11/steps-towards-some-docker-ipython-magic-hard-coded-magic-sketch-for-contentmine/).

**Comment by tarrow** [comment] 2016-09-23 09:53
I'm closing this because it seem that the problem is solved; please open a new bug if you're still having trouble installing

**Closed by tarrow** 2016-09-23 09:53 UTC
